name: "Assignees4label"
on:
  issues:
    types: [labeled]

jobs:
  set-assignees:
    if: contains( fromJSON('["outreach", "adoption", "metadata_schema"]'), github.event.label.name) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kyanagimoto/assignee4label@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: '.github/assignee4label.yml'